# Generated by Django 4.2.7 on 2023-12-12 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('helpdeskapp', '0005_alter_ticket_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_assigned_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ITuser',
        ),
    ]
