# Generated by Django 4.2.7 on 2023-12-21 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdeskapp', '0007_ticket_closed_at_alter_ticket_assigned_to'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-created_at'], 'permissions': [('can_change_status', 'Can change status'), ('can_change_priority', 'Can change priority')]},
        ),
    ]
