# Generated by Django 4.2.7 on 2023-12-22 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdeskapp', '0008_alter_ticket_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-assigned_to'], 'permissions': [('can_change_status', 'Can change status'), ('can_change_priority', 'Can change priority')]},
        ),
    ]
