# Generated by Django 4.2.7 on 2024-01-04 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdeskapp', '0010_alter_ticket_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-created_at']},
        ),
    ]
